substitutions:
  my_name: ping-sensor

esphome:
  name: ${my_name}
  platform: ESP32
  board: lolin32

logger:

web_server:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Ping
    password: !secret wifi_ap_password

captive_portal:

external_components:
  - source:
      type: local
      path: ../components

sensor:
  - platform: ping
    ip_address: 8.8.8.8
    num_attempts: 17
    timeout: 1sec
    loss:
      name: Packet loss
    latency:
      name: Latency
      accuracy_decimals: 3
